/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * The page that display the Individual Domestic and Interline reports based on the logged in advisor
 */
public class IndividualSales extends javax.swing.JFrame {
    
    int mousepX;
    int mousepY;

    /**
     * Creates new form IndividualSales
     */
    public IndividualSales() {
        initComponents();
    }
/**
     * 
     * @param staffID sets staffID to StaffIDLabel to be displayed on ManageAdvisors page.
     * @param firstName sets firstName to StaffNameLabel to be displayed on ManageAdvisors page.
     * @param role  sets role to StaffRoleLabel to be displayed on ManageAdvisors page.
     */
    public IndividualSales(String staffID,String firstName, String role) {
        initComponents();
        StaffIDLable.setText(staffID);
        StaffNameLable.setText(firstName);
        StaffRoleLable.setText(role);
        DomesticPanel.setVisible(false);
        //PrintButton.doClick();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PrintButton = new javax.swing.JButton();
        ReportTypeComboBox = new javax.swing.JComboBox<>();
        DomesticPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTableDomestic = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TotalTableDomestic = new javax.swing.JTable();
        InterlinePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportTableInterline = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TotalTableInterline = new javax.swing.JTable();
        FromDate = new org.jdesktop.swingx.JXDatePicker();
        ToDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        StaffRoleLable = new javax.swing.JLabel();
        StaffIDLable = new javax.swing.JLabel();
        StaffNameLable = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrintButton.setText("Print");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 100, 30));

        ReportTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestic", "Interline" }));
        jPanel1.add(ReportTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        ReportTableDomestic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Original Issued Number", "Fare Base (Local)", "Fare Base (USD)", "Taxes", "Total Amoutn Paid", "Cash Paymet", "Card Paymet", "Commisssion Rate", "Total Amount Paid", "Commission Amount"
            }
        ));
        jScrollPane1.setViewportView(ReportTableDomestic);

        TotalTableDomestic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NBR of TKTS", "Fare Base(Local) Total", "Fare Base(USD) Tota", "Taxes Total", "Total Amount Paid", "Total Cash Payment", "Total Card Payment", "Total Commission Amounts", "Net Amounts for Agent Debit", "Total Nett Amount For Bank Remittance to \"Air Via\""
            }
        ));
        jScrollPane4.setViewportView(TotalTableDomestic);
        if (TotalTableDomestic.getColumnModel().getColumnCount() > 0) {
            TotalTableDomestic.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout DomesticPanelLayout = new javax.swing.GroupLayout(DomesticPanel);
        DomesticPanel.setLayout(DomesticPanelLayout);
        DomesticPanelLayout.setHorizontalGroup(
            DomesticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DomesticPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DomesticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        DomesticPanelLayout.setVerticalGroup(
            DomesticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DomesticPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(DomesticPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, 340));

        ReportTableInterline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Original Issued Number", "USD", "USD/Local", "Local", "Local Taxes", "Other Taxes", "Total Documents Amount", "Cash Payment", "Card Payment", "Commisssion Rate", "Total Amount Paid", "Commission Amount", "Non Assess-Amounts"
            }
        ));
        jScrollPane2.setViewportView(ReportTableInterline);

        TotalTableInterline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NBR of TKTS", "USD", "USD/Local", "Local", "Local Taxes", "Other Taxes", "Total Documented Amount", "Total Cash", "Total Card", "Total Amount Paid", "Non Asses Amount Total ", "Total Commission Amount", "Net Amount For Aget Debit", "Total Nett AMount For Bank Permittence to 'Air Via'"
            }
        ));
        jScrollPane5.setViewportView(TotalTableInterline);

        javax.swing.GroupLayout InterlinePanelLayout = new javax.swing.GroupLayout(InterlinePanel);
        InterlinePanel.setLayout(InterlinePanelLayout);
        InterlinePanelLayout.setHorizontalGroup(
            InterlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterlinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InterlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        InterlinePanelLayout.setVerticalGroup(
            InterlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterlinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(InterlinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1288, -1));
        jPanel1.add(FromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));
        jPanel1.add(ToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 380, -1, -1));

        jLabel1.setText("Individual Sales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 76, 113));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1300, 460));

        jPanel5.setBackground(new java.awt.Color(41, 76, 113));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(54, 97, 144));
        Home.setForeground(new java.awt.Color(204, 204, 204));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(86, 86, 86))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Travel Advisor");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 10));

        jPanel15.setBackground(new java.awt.Color(252, 68, 69));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Log Out");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(80, 80, 80))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Name:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Staff ID:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("Role:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 31, -1));

        StaffRoleLable.setForeground(java.awt.Color.white);
        StaffRoleLable.setText("jLabel9");
        jPanel5.add(StaffRoleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        StaffIDLable.setForeground(java.awt.Color.white);
        StaffIDLable.setText("jLabel8");
        jPanel5.add(StaffIDLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        StaffNameLable.setForeground(java.awt.Color.white);
        StaffNameLable.setText("jLabel9");
        jPanel5.add(StaffNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 430));

        jPanel14.setBackground(new java.awt.Color(238, 238, 238));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel14MouseDragged(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 20));

        jPanel16.setBackground(new java.awt.Color(238, 238, 238));
        jPanel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel16MouseDragged(evt);
            }
        });
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel16MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1510, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
        int staffID=Integer.parseInt(StaffIDLable.getText());
        String type=(String) ReportTypeComboBox.getSelectedItem();
        Connection con=null;
        String query;
        PreparedStatement ps;
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String from = dateFormat.format(FromDate.getDate());
        String to = dateFormat.format(ToDate.getDate());
        if("Domestic".equals(type)){
            DomesticPanel.setVisible(true);
            InterlinePanel.setVisible(false);
            System.out.println("DOMESTIC main");
            query="SELECT\n" +
"blanks.blankID AS '1', ticketsales.amountPaid - taxes.local AS '2', (ticketsales.amountPaid - taxes.local) * exchangerate.exchangeRate AS '3',\n" +
"Taxes.local AS '4',\n" +
"ticketsales.amountPaid AS '5' ,\n" +
"(SELECT ticketsales.amountPaid  WHERE paymentdetails.paymentType LIKE '%Cash%') AS '6',\n" +
"(SELECT ticketsales.amountPaid  WHERE paymentdetails.paymentType LIKE '%Card%') AS '7', commisionrate.commissionRate AS '8',\n" +
"ticketsales.amountPaid AS '9',\n" +
"ticketsales.amountPaid * commisionrate.commissionRate AS '10'\n" +
"FROM blanks\n" +
"LEFT JOIN Taxes ON blanks.TaxID = Taxes.TaxID\n" +
"LEFT JOIN exchangerate ON blanks.exchangeRateID = exchangerate.exchangeRateID\n" +
"LEFT JOIN commisionrate ON blanks.commissionRateID = commisionrate.commissionRateID\n" +
"LEFT JOIN paymentdetails ON blanks.blankID = paymentdetails.blankID\n" +
"LEFT JOIN ticketsales ON blanks.blankID = ticketsales.blankID\n" +
"WHERE blanks.staffID = "+staffID+" AND (ticketsales.currency = 'Local%' AND ticketsales.dateSold BETWEEN '"+from+"' AND '"+to+"' AND blanks.blankID LIKE '1%' OR blanks.blankID LIKE '2_%')";
        
        
         try{
            con=MyConnection.getConnection();
            con.setAutoCommit(false);
            System.out.println("Get Connection");
            ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)ReportTableDomestic.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getString("1"),rs.getFloat("2"),rs.getFloat("3"),rs.getFloat("4"),rs.getFloat("5"),rs.getFloat("6"),rs.getFloat("7"),rs.getFloat("8"),rs.getFloat("9"),rs.getFloat("10")};
                tm.addRow(o);
            }

            updateTotal();
            con.setAutoCommit(true);
            con.close();
            System.out.println("Close Connection");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    
        
        
        
    }else{
            DomesticPanel.setVisible(false);
            InterlinePanel.setVisible(true);
            System.out.println("interline main");
            query="SELECT blanks.blankID AS '1',\n" +
"(ticketsales.amountPaid - taxes.local - taxes.others) * exchangerate.exchangeRate AS '2',\n" +
"exchangerate.exchangeRate AS '3',\n" +
"ticketsales.amountPaid - taxes.local - taxes.others AS '4',\n" +
"Taxes.local AS '5',\n" +
"Taxes.Others AS '6',\n" +
"ticketsales.amountPaid  AS '7',\n" +
"(SELECT ticketsales.amountPaid  WHERE paymentdetails.paymentType LIKE '%Cash%') AS '8',\n" +
"(SELECT ticketsales.amountPaid  WHERE paymentdetails.paymentType LIKE '%Card%') AS '9' ,\n" +
"commisionrate.commissionRate AS '10',\n" +
"(SELECT ticketsales.amountPaid  WHERE blanks.status = 'Paid') AS '11',\n" +
"ticketsales.amountPaid * commisionrate.commissionRate AS '12',\n" +
"taxes.local + taxes.others AS '13'\n" +
"FROM blanks\n" +
"LEFT JOIN Taxes ON blanks.TaxID = Taxes.TaxID\n" +
"LEFT JOIN exchangerate ON blanks.exchangeRateID = exchangerate.exchangeRateID\n" +
"LEFT JOIN commisionrate ON blanks.commissionRateID = commisionrate.commissionRateID\n" +
"LEFT JOIN paymentdetails ON blanks.blankID = paymentdetails.blankID\n" +
"LEFT JOIN ticketsales ON blanks.blankID = ticketsales.blankID\n" +
"WHERE blanks.staffID = "+staffID+" AND blanks.blankID LIKE '4%' AND ticketsales.dateSold BETWEEN '"+from+"' AND '"+to+"'";
        try{
            con=MyConnection.getConnection();
            con.setAutoCommit(false);
            System.out.println("Get Connection");
            ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)ReportTableInterline.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getString("1"),rs.getFloat("2"),rs.getFloat("3"),rs.getFloat("4"),rs.getFloat("5"),rs.getFloat("6"),rs.getFloat("7"),rs.getFloat("8"),rs.getFloat("9"),rs.getFloat("10"),rs.getFloat("11"),rs.getFloat("12"),rs.getFloat("13")};
                tm.addRow(o);
            }

            updateTotal();
            con.setAutoCommit(true);
            con.close();
            System.out.println("Close Connection");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    }//GEN-LAST:event_PrintButtonActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        travelAd ta =new travelAd(StaffIDLable.getText(),
            StaffNameLable.getText(),
            StaffRoleLable.getText());

        ta.setVisible(true);
        ta.pack();
        ta.setLocationRelativeTo(null); //puts in the center of the screen
        //  sls.setDefultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //hides previos page
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
        Home.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        // TODO add your handling code here:
        Home.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_HomeMouseExited

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMousePressed

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        loginFrame lf = new loginFrame();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252, 116, 117));
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252,68,69));
    }//GEN-LAST:event_jPanel15MouseExited

    private void jPanel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseDragged
        int cordX= evt.getXOnScreen();
        int cordY = evt.getYOnScreen();

        this.setLocation(cordX-mousepX, cordY-mousepY);
    }//GEN-LAST:event_jPanel14MouseDragged

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel14MousePressed

    private void jPanel16MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseDragged
        int cordX= evt.getXOnScreen();
        int cordY = evt.getYOnScreen();

        this.setLocation(cordX-mousepX, cordY-mousepY);
    }//GEN-LAST:event_jPanel16MouseDragged

    private void jPanel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel16MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * Depending on the dropbox at IndividualSales report page it will display the total information on the report for the logged in advisor
    **/
    public void updateTotal(){
        int staffID=Integer.parseInt(StaffIDLable.getText());
        String type=(String) ReportTypeComboBox.getSelectedItem();
        Connection con=null;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String from = dateFormat.format(FromDate.getDate());
        String to = dateFormat.format(ToDate.getDate());
        String query;
       PreparedStatement ps;
       if(type=="Domestic"){
           System.out.println("DOMESTIC total");
        query="SELECT COUNT(ticketsales.blankID) AS '1', SUM(ticketsales.amountPaid) - SUM(taxes.local) AS '2', (SUM(ticketsales.amountPaid) - SUM(taxes.local)) * exchangerate.exchangeRate AS '3', SUM(Taxes.local) AS '4', SUM(ticketsales.amountPaid) AS '5', (SELECT SUM(ticketsales.amountPaid) WHERE paymentdetails.paymentType LIKE '%Cash%') AS '6', (SELECT SUM(ticketsales.amountPaid) WHERE paymentdetails.paymentType LIKE '%Card%') AS '7', SUM(commisionrate.commissionRate * ticketsales.amountPaid) AS '8', SUM(ticketsales.amountPaid) - SUM(ticketsales.amountPaid * commisionrate.commissionRate) AS '9', SUM(ticketsales.amountPaid) + SUM(taxes.Local)-SUM(commisionrate.commissionRate * ticketsales.amountPaid) AS '10'\n" +
"FROM blanks\n" +
"\n" +
"LEFT JOIN exchangerate ON blanks.exchangeRateID = exchangerate.exchangeRateID\n" +
"LEFT JOIN Taxes ON blanks.TaxID = Taxes.TaxID\n" +
"LEFT JOIN commisionrate ON blanks.commissionRateID = commisionrate.commissionRateID\n" +
"LEFT JOIN paymentdetails ON blanks.blankID = paymentdetails.blankID\n" +
"LEFT JOIN ticketsales ON blanks.blankID = ticketsales.blankID\n" +
"WHERE blanks.staffID = "+staffID+"  AND (ticketsales.status = 'sold' AND ticketsales.dateSold BETWEEN '"+from+"' AND '"+to+"' AND blanks.blankID LIKE '1%' OR blanks.blankID LIKE '2%')";
        
         try{  
         con=MyConnection.getConnection();
         con.setAutoCommit(false);
         System.out.println("Get Connection");
         ps=con.prepareStatement(query);
         ResultSet rs=ps.executeQuery();
         DefaultTableModel tm=(DefaultTableModel)TotalTableDomestic.getModel();
         tm.setRowCount(0); 
         while(rs.next()){
             Object o[]={rs.getInt("1"),rs.getFloat("2"),rs.getFloat("3"),rs.getFloat("4"),rs.getFloat("5"),rs.getFloat("6"),rs.getFloat("7"),rs.getFloat("8"),rs.getFloat("9"),rs.getFloat("10")};
             tm.addRow(o);
         }  
         con.setAutoCommit(true);
         con.close();
         System.out.println("Close Connection");
         
    }                                           
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e);
    }
        
        
        
        
        
        
       }else{
           System.out.println("INterline total");
         query="SELECT COUNT(blanks.blankID) AS '1', SUM(ticketsales.amountPaid - taxes.local - taxes.others) * exchangerate.exchangeRate  AS '2' ,\n" +
"SUM(ticketsales.amountPaid - taxes.local - taxes.others) AS '3' ,\n" +
"SUM(Taxes.local)  AS '4' ,\n" +
"SUM(Taxes.Others) AS '5',\n" +
"SUM(ticketsales.amountPaid) + SUM(Taxes.local) + SUM(Taxes.Others) AS '6',\n" +
"(SELECT SUM(ticketsales.amountPaid) WHERE paymentdetails.paymentType LIKE '%Cash%') AS '7' ,\n" +
"(SELECT SUM(ticketsales.amountPaid) WHERE paymentdetails.paymentType LIKE '%Card%') AS '8' ,\n" +
"ticketsales.amountPaid AS '9' ,\n" +
"SUM(commisionrate.commissionRate * ticketsales.amountPaid) AS '10',\n" +
"SUM(ticketsales.amountPaid) - SUM(commisionrate.commissionRate * ticketsales.amountPaid)  AS '11', SUM(ticketsales.amountPaid + taxes.local + taxes.others) - SUM(commisionrate.commissionRate * ticketsales.amountPaid) AS '12', SUM(taxes.local) + SUM(taxes.others) AS '13'\n" +
"\n" +
"FROM blanks\n" +
"LEFT JOIN exchangerate ON blanks.exchangeRateID = exchangerate.exchangeRateID\n" +
"LEFT JOIN Taxes ON blanks.TaxID = Taxes.TaxID\n" +
"LEFT JOIN commisionrate ON blanks.commissionRateID = commisionrate.commissionRateID\n" +
"LEFT JOIN paymentdetails ON blanks.blankID = paymentdetails.blankID\n" +
"LEFT JOIN ticketsales ON blanks.blankID = ticketsales.blankID\n" +
"WHERE blanks.staffid = "+staffID+" AND (ticketsales.status = 'Paid' AND blanks.blankID LIKE '4_%' AND ticketsales.dateSold BETWEEN '"+from+"' AND '"+to+"')";
         
     try{  
         
         con=MyConnection.getConnection();
         con.setAutoCommit(false);
         System.out.println("Get Connection");
         ps=con.prepareStatement(query);
         ResultSet rs=ps.executeQuery();
         DefaultTableModel tm=(DefaultTableModel)TotalTableInterline.getModel();
         tm.setRowCount(0); 
         while(rs.next()){
             Object o[]={rs.getInt("1"),rs.getFloat("2"),"-",rs.getFloat("3"),rs.getFloat("4"),rs.getFloat("5"),rs.getFloat("6"),rs.getFloat("7"),rs.getFloat("8"),rs.getFloat("9"),rs.getFloat("10"),rs.getFloat("11"),rs.getFloat("12"),rs.getFloat("13")};
             tm.addRow(o);
         }  
         con.setAutoCommit(true);
         con.close();
         System.out.println("Close Connection");
         
    }                                           
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e);
    }
    
    }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DomesticPanel;
    private org.jdesktop.swingx.JXDatePicker FromDate;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel InterlinePanel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTable ReportTableDomestic;
    private javax.swing.JTable ReportTableInterline;
    private javax.swing.JComboBox<String> ReportTypeComboBox;
    private javax.swing.JLabel StaffIDLable;
    private javax.swing.JLabel StaffNameLable;
    private javax.swing.JLabel StaffRoleLable;
    private org.jdesktop.swingx.JXDatePicker ToDate;
    private javax.swing.JTable TotalTableDomestic;
    private javax.swing.JTable TotalTableInterline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
