/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_system;

import java.awt.Color;

/**
 * system admin page that has admin operation and access to the pages that only admin can use.
 */
public class systemAdmin extends javax.swing.JFrame {
    
    int mousepX;
    int mousepY;

    /**
     * Creates new form systemAdmin
     */
    public systemAdmin() {
        initComponents();
    }
    
    /** As soon as page is played, systemAdmin() will run automatically without any user actions.
     * 
     * @param staffID Gets staffID from database and displays it on page.
     * @param firstName Gets firstName from database and displays it on page.
     * @param role Gets firstName from database and displays it on page.
     */
     public systemAdmin(String staffID,String firstName, String role) {
        initComponents();
        StaffIDLable.setText(staffID);
        StaffNameLable.setText(firstName);
        StaffRoleLable.setText(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        ManageTravelAdvisor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ManageBlanks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DatabaseBackup = new javax.swing.JPanel();
        Database = new javax.swing.JLabel();
        StockReport = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RecordPayment = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ReturnBlanks = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        StaffNameLable = new javax.swing.JLabel();
        StaffIDLable = new javax.swing.JLabel();
        StaffRoleLable = new javax.swing.JLabel();
        RecordPayment1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(41, 76, 113));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageTravelAdvisor.setBackground(new java.awt.Color(54, 97, 144));
        ManageTravelAdvisor.setForeground(new java.awt.Color(204, 204, 204));
        ManageTravelAdvisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageTravelAdvisorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageTravelAdvisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageTravelAdvisorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageTravelAdvisorMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Travel Advisor");

        javax.swing.GroupLayout ManageTravelAdvisorLayout = new javax.swing.GroupLayout(ManageTravelAdvisor);
        ManageTravelAdvisor.setLayout(ManageTravelAdvisorLayout);
        ManageTravelAdvisorLayout.setHorizontalGroup(
            ManageTravelAdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageTravelAdvisorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        ManageTravelAdvisorLayout.setVerticalGroup(
            ManageTravelAdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageTravelAdvisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(ManageTravelAdvisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        ManageBlanks.setBackground(new java.awt.Color(54, 97, 144));
        ManageBlanks.setForeground(new java.awt.Color(204, 204, 204));
        ManageBlanks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageBlanksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageBlanksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageBlanksMouseExited(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Blanks");

        javax.swing.GroupLayout ManageBlanksLayout = new javax.swing.GroupLayout(ManageBlanks);
        ManageBlanks.setLayout(ManageBlanksLayout);
        ManageBlanksLayout.setHorizontalGroup(
            ManageBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageBlanksLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        ManageBlanksLayout.setVerticalGroup(
            ManageBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageBlanksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(ManageBlanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, -1));

        DatabaseBackup.setBackground(new java.awt.Color(54, 97, 144));
        DatabaseBackup.setForeground(new java.awt.Color(204, 204, 204));
        DatabaseBackup.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DatabaseBackupAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        DatabaseBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatabaseBackupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DatabaseBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DatabaseBackupMouseExited(evt);
            }
        });

        Database.setForeground(new java.awt.Color(255, 255, 255));
        Database.setText("Backup & Restore Database");

        javax.swing.GroupLayout DatabaseBackupLayout = new javax.swing.GroupLayout(DatabaseBackup);
        DatabaseBackup.setLayout(DatabaseBackupLayout);
        DatabaseBackupLayout.setHorizontalGroup(
            DatabaseBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabaseBackupLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Database)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        DatabaseBackupLayout.setVerticalGroup(
            DatabaseBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabaseBackupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Database, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(DatabaseBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, -1));

        StockReport.setBackground(new java.awt.Color(54, 97, 144));
        StockReport.setForeground(new java.awt.Color(204, 204, 204));
        StockReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockReportMouseExited(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View Stock Turnover Report");

        javax.swing.GroupLayout StockReportLayout = new javax.swing.GroupLayout(StockReport);
        StockReport.setLayout(StockReportLayout);
        StockReportLayout.setHorizontalGroup(
            StockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockReportLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );
        StockReportLayout.setVerticalGroup(
            StockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(StockReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System Admin");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Role:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 31, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Staff ID:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 10));

        RecordPayment.setBackground(new java.awt.Color(54, 97, 144));
        RecordPayment.setForeground(new java.awt.Color(204, 204, 204));
        RecordPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecordPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecordPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecordPaymentMouseExited(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("View Logs");

        javax.swing.GroupLayout RecordPaymentLayout = new javax.swing.GroupLayout(RecordPayment);
        RecordPayment.setLayout(RecordPaymentLayout);
        RecordPaymentLayout.setHorizontalGroup(
            RecordPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecordPaymentLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(74, 74, 74))
        );
        RecordPaymentLayout.setVerticalGroup(
            RecordPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(RecordPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, -1));

        jPanel15.setBackground(new java.awt.Color(252, 68, 69));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Log Out");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(80, 80, 80))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        ReturnBlanks.setBackground(new java.awt.Color(54, 97, 144));
        ReturnBlanks.setForeground(new java.awt.Color(204, 204, 204));
        ReturnBlanks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBlanksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReturnBlanksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnBlanksMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Return Blanks");

        javax.swing.GroupLayout ReturnBlanksLayout = new javax.swing.GroupLayout(ReturnBlanks);
        ReturnBlanks.setLayout(ReturnBlanksLayout);
        ReturnBlanksLayout.setHorizontalGroup(
            ReturnBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnBlanksLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        ReturnBlanksLayout.setVerticalGroup(
            ReturnBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnBlanksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(ReturnBlanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, -1));

        StaffNameLable.setForeground(java.awt.Color.white);
        StaffNameLable.setText("jLabel9");
        jPanel5.add(StaffNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        StaffIDLable.setForeground(java.awt.Color.white);
        StaffIDLable.setText("jLabel8");
        jPanel5.add(StaffIDLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        StaffRoleLable.setForeground(java.awt.Color.white);
        StaffRoleLable.setText("jLabel9");
        jPanel5.add(StaffRoleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        RecordPayment1.setBackground(new java.awt.Color(54, 97, 144));
        RecordPayment1.setForeground(new java.awt.Color(204, 204, 204));
        RecordPayment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecordPayment1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecordPayment1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecordPayment1MouseExited(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Record Payment");

        javax.swing.GroupLayout RecordPayment1Layout = new javax.swing.GroupLayout(RecordPayment1);
        RecordPayment1.setLayout(RecordPayment1Layout);
        RecordPayment1Layout.setHorizontalGroup(
            RecordPayment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordPayment1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel16)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        RecordPayment1Layout.setVerticalGroup(
            RecordPayment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(RecordPayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 510));

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 76, 113));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ATS Software");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Version Software: 1.0");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("DEVELOPED BY RUNTIME TERROR (TEAM 14)");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 860, 510));

        jPanel14.setBackground(new java.awt.Color(238, 238, 238));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel14MouseDragged(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(41, 76, 113));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(1052, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageTravelAdvisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageTravelAdvisorMouseClicked
        ManageAdvisors manageAd = new ManageAdvisors(StaffIDLable.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        manageAd.setVisible(true);
        manageAd.pack();
        manageAd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ManageTravelAdvisorMouseClicked

    private void ManageTravelAdvisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageTravelAdvisorMouseEntered
        // TODO add your handling code here:
        ManageTravelAdvisor.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_ManageTravelAdvisorMouseEntered

    private void ManageTravelAdvisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageTravelAdvisorMouseExited
        // TODO add your handling code here:
        ManageTravelAdvisor.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_ManageTravelAdvisorMouseExited

    private void ManageTravelAdvisorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageTravelAdvisorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageTravelAdvisorMousePressed

    private void ManageBlanksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBlanksMouseClicked
        manageBlanks mb = new manageBlanks(StaffIDLable.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        mb.setVisible(true);
        mb.pack();
        mb.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_ManageBlanksMouseClicked

    private void ManageBlanksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBlanksMouseEntered
        // TODO add your handling code here:
        ManageBlanks.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_ManageBlanksMouseEntered

    private void ManageBlanksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBlanksMouseExited
        // TODO add your handling code here:
        ManageBlanks.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_ManageBlanksMouseExited

    private void DatabaseBackupAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DatabaseBackupAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseBackupAncestorAdded

    private void DatabaseBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatabaseBackupMouseClicked
        BackupAndRestore lf = new BackupAndRestore(StaffIDLable.getText(),
            StaffNameLable.getText(),
            StaffRoleLable.getText());
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_DatabaseBackupMouseClicked

    private void DatabaseBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatabaseBackupMouseEntered
        // TODO add your handling code here:
        DatabaseBackup.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_DatabaseBackupMouseEntered

    private void DatabaseBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatabaseBackupMouseExited
        // TODO add your handling code here:
        DatabaseBackup.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_DatabaseBackupMouseExited

    private void StockReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockReportMouseClicked
        StockTurnoverReport stockTurnover = new StockTurnoverReport(StaffIDLable.getText(),
            StaffNameLable.getText(),
            StaffRoleLable.getText());
        stockTurnover.setVisible(true);
        stockTurnover.pack();
        stockTurnover.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_StockReportMouseClicked

    private void StockReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockReportMouseEntered
        // TODO add your handling code here:
        StockReport.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_StockReportMouseEntered

    private void StockReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockReportMouseExited
        // TODO add your handling code here:
        StockReport.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_StockReportMouseExited

    private void RecordPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPaymentMouseClicked
        viewLogs lf = new viewLogs(StaffIDLable.getText(), StaffNameLable.getText(), StaffRoleLable.getText());
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_RecordPaymentMouseClicked

    private void RecordPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPaymentMouseEntered
        // TODO add your handling code here:
        RecordPayment.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_RecordPaymentMouseEntered

    private void RecordPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPaymentMouseExited
        // TODO add your handling code here:
        RecordPayment.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_RecordPaymentMouseExited

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        loginFrame lf = new loginFrame();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252, 116, 117));
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252,68,69));
    }//GEN-LAST:event_jPanel15MouseExited

    private void ReturnBlanksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBlanksMouseClicked
        // TODO add your handling code here:
        ManageBlankSysAdmin manageBlank = new ManageBlankSysAdmin(StaffIDLable.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        manageBlank.setVisible(true);
        manageBlank.pack();
        manageBlank.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ReturnBlanksMouseClicked

    private void ReturnBlanksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBlanksMouseEntered
        // TODO add your handling code here:
        ReturnBlanks.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_ReturnBlanksMouseEntered

    private void ReturnBlanksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBlanksMouseExited
        // TODO add your handling code here:
        ReturnBlanks.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_ReturnBlanksMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseDragged
        int cordX= evt.getXOnScreen();
        int cordY = evt.getYOnScreen();

        this.setLocation(cordX-mousepX, cordY-mousepY);
    }//GEN-LAST:event_jPanel14MouseDragged

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel14MousePressed

    private void RecordPayment1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPayment1MouseClicked
        // TODO add your handling code here:
        RecordPayment rp = new RecordPayment(StaffIDLable.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        rp.setVisible(true);
        rp.pack();
        rp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RecordPayment1MouseClicked

    private void RecordPayment1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPayment1MouseEntered
        // TODO add your handling code here:
        RecordPayment1.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_RecordPayment1MouseEntered

    private void RecordPayment1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordPayment1MouseExited
        // TODO add your handling code here:
        RecordPayment1.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_RecordPayment1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(systemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new systemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Database;
    private javax.swing.JPanel DatabaseBackup;
    private javax.swing.JPanel ManageBlanks;
    private javax.swing.JPanel ManageTravelAdvisor;
    private javax.swing.JPanel RecordPayment;
    private javax.swing.JPanel RecordPayment1;
    private javax.swing.JPanel ReturnBlanks;
    private javax.swing.JLabel StaffIDLable;
    private javax.swing.JLabel StaffNameLable;
    private javax.swing.JLabel StaffRoleLable;
    private javax.swing.JPanel StockReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
