
package java_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *The travel advisor page that shows the tickets that the advisor has sold as well as the list of all his blanks that was assigned and their status. Navigation to other pages that advisor need to make sales and record payment.
 * 
 */
public class travelAd extends javax.swing.JFrame {
    
    int mousepX;
    int mousepY;

    /**
     * Creates new form travelAd
     */
    public travelAd() {
        initComponents();
    }
    
    /** As soon as page is displayed, travelAd() will run automatically without any user action.
     * 
     * @param staffID Gets staffID from database and displays it on page.
     * @param firstName Gets firstName from database and displays it on page.
     * @param role Gets firstName from database and displays it on page.
     * .doClick() will act as if BlankTableButton is pressed on without user pressing it.
     */
    public travelAd(String staffID,String firstName, String role) {
        initComponents();
        StaffIDLabel.setText(staffID);
        StaffNameLable.setText(firstName);
        StaffRoleLable.setText(role);
        BlankTableButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BlankTableButton = new javax.swing.JButton();
        BlanksType = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        AdvisorSaleTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ExchangeRateField = new javax.swing.JTextField();
        UpdateExchangeRateButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CurrencyCodeField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TicketNumberField = new javax.swing.JTextField();
        RefundTicketButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        BlankNumberField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        VoidBlankButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdvisorBlanksTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        StaffNameLable = new javax.swing.JLabel();
        StaffIDLabel = new javax.swing.JLabel();
        StaffRoleLable = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlankTableButton.setText("Refresh Tables");
        BlankTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlankTableButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BlankTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 136, -1));

        BlanksType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "444", "440", "420", "201", "101" }));
        BlanksType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlanksTypeActionPerformed(evt);
            }
        });
        jPanel1.add(BlanksType, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, 30));

        AdvisorSaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Ticket ID", "Status", "Customer Name", "Customer Surname", "Amount", "Amount Paid", "BlankID"
            }
        ));
        jScrollPane3.setViewportView(AdvisorSaleTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 840, 120));

        jLabel15.setText("Advisors Sales:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setText("Advisors Blanks");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(62, 112, 165));

        UpdateExchangeRateButton.setText("Update Exchange Rate");
        UpdateExchangeRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExchangeRateButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Exchange Rate :");

        jLabel10.setText("Currency Code (IATA) :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateExchangeRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ExchangeRateField)
                            .addComponent(CurrencyCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ExchangeRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CurrencyCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateExchangeRateButton)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 280, 110));

        jPanel3.setBackground(new java.awt.Color(62, 112, 165));

        jLabel3.setText("Ticket Number:");

        RefundTicketButton.setText("Refund Ticket");
        RefundTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefundTicketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefundTicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TicketNumberField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TicketNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RefundTicketButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 220, 110));

        jPanel4.setBackground(new java.awt.Color(62, 112, 165));

        jLabel1.setText("Blank Number:");

        VoidBlankButton.setText("Void Blank");
        VoidBlankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoidBlankButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlankNumberField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VoidBlankButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlankNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoidBlankButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 230, 110));

        AdvisorBlanksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staffID", "Type", "Blank ID ", "Status", "Assigned Coupons", "Date"
            }
        ));
        jScrollPane2.setViewportView(AdvisorBlanksTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 840, 130));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 76, 113));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, -1));

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Home");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 860, 510));

        jPanel5.setBackground(new java.awt.Color(41, 76, 113));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(54, 97, 144));
        jPanel6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        jPanel8.setBackground(new java.awt.Color(54, 97, 144));
        jPanel8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sell Ticket");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(74, 74, 74))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, -1));

        jPanel10.setBackground(new java.awt.Color(54, 97, 144));
        jPanel10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("View Individiual Sales Report");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Travel Advisor");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Role:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 31, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Staff ID:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 10));

        jPanel12.setBackground(new java.awt.Color(54, 97, 144));
        jPanel12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Record Payment");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel18)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, -1));

        jPanel15.setBackground(new java.awt.Color(252, 68, 69));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Log Out");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(80, 80, 80))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        StaffNameLable.setForeground(java.awt.Color.white);
        StaffNameLable.setText("jLabel9");
        jPanel5.add(StaffNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        StaffIDLabel.setForeground(java.awt.Color.white);
        StaffIDLabel.setText("jLabel8");
        jPanel5.add(StaffIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        StaffRoleLable.setForeground(java.awt.Color.white);
        StaffRoleLable.setText("jLabel9");
        jPanel5.add(StaffRoleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 510));

        jPanel14.setBackground(new java.awt.Color(238, 238, 238));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel14MouseDragged(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** When JButton is pressed, SQL query is executed which will display blankID, staffID
     * , type, status, date, dateRecieved, Coupons from blank table in database into AdvisorBlanksTable.
     * 
     */
    private void BlankTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlankTableButtonActionPerformed
        // TODO add your handling code here:
        
        String staffID = StaffIDLabel.getText();
        String btype=(String) BlanksType.getSelectedItem();
        Connection con=null;
        PreparedStatement ps;
        String query;
        if(btype=="All"){
            query="SELECT `blankID`, `staffID`, `type`, `status`, `dateRecieved`, `Coupons` FROM `blanks` WHERE staffID="+staffID+" AND type";
        }else{
            query="SELECT `blankID`, `staffID`, `type`, `status`, `dateRecieved`, `Coupons` FROM `blanks` WHERE staffID="+staffID+" AND type="+btype;
        }
        try{
            con=MyConnection.getConnection();
            System.out.println("Get Connection");
            ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)AdvisorBlanksTable.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getString("staffID"),rs.getString("type"),rs.getString("blankID"),rs.getString("status"),rs.getString("Coupons"),rs.getString("dateRecieved")};
                tm.addRow(o);
            }
            con.close();
            System.out.println("Close Connection");
            
            ticketTableUpdate();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"No Staff ID was entered");
        }

    }//GEN-LAST:event_BlankTableButtonActionPerformed

    private void BlanksTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlanksTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlanksTypeActionPerformed

    /** Function executes SQL query which will display tickets on AdvisorSalesTable 
     *that the advisors has sold. 
     *
     */
    public void ticketTableUpdate(){
        // TODO add your handling code here:
        Connection con=null;
        String staffID = StaffIDLabel.getText();
        
        PreparedStatement ps;
        String query="SELECT blankID,ticketID, c.DOB, ts.customerID, amount, amountPaid, status, c.firstName, c.lastName FROM customer AS c INNER JOIN ticketsales AS ts WHERE ts.customerID=c.customerID AND staffID="+staffID +";";

        try{
            con=MyConnection.getConnection();
            System.out.println("Get Connection");
            ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)AdvisorSaleTable.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("customerID"),rs.getInt("ticketID"),rs.getString("status"),rs.getString("c.firstName"),rs.getString("c.lastName"),rs.getInt("amount"),rs.getInt("amountPaid"),rs.getString("blankID")};
                tm.addRow(o);
            }
            con.close();
            System.out.println("Close Connection");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
}
    
    
    /** JButton when pressed on, will take ExchangeRateField and CurrencyCodeField as an string array and insert into exchangerate table as well as inserting
     * USDAmount which is defaulted as 1 and date which is the systems current date.
     *  
     */
    private void UpdateExchangeRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExchangeRateButtonActionPerformed
        // TODO add your handling code here:
        String[] exchangeRateLog = {ExchangeRateField.getText(),CurrencyCodeField.getText()};
         CreateLog.writeLog("C:/Users/ASUS/Desktop/Team Project jin pages/java_system_with_GUI_Final (1)/java_system/LOGS FOR THE DEMO/ExchangeRateLog.txt"
            ,exchangeRateLog);
        Connection con=null;
        PreparedStatement ps;
        String query="INSERT INTO `exchangerate`(`exchangeRateID`, `exchangeRate`,`localCurrencyName`,`date`) VALUES (?,?,?,?)";

        try{
            con=MyConnection.getConnection();
            ps=con.prepareStatement(query);

            ps.setInt(1,(int) (Math.random() * ( 9999 - 1000 )));
            ps.setFloat(2,Float.valueOf(ExchangeRateField.getText()));
            ps.setString(3,CurrencyCodeField.getText());

            ps.setString(4,new SimpleDateFormat("yyyy-MM-dd-hh-mm-ss").format(new Date()));

            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"Exchange Rate Recorded");
                con.close();
                System.out.println("Close Connection");
            }

        }catch (SQLException ex){
            Logger.getLogger(RecordPayment.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_UpdateExchangeRateButtonActionPerformed

    private void RefundTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefundTicketButtonActionPerformed
        // TODO add your handling code here:

        String ticketID= TicketNumberField.getText();
        Connection con=null;
         PreparedStatement pst;
         ResultSet rs;
        con=MyConnection.getConnection();
        String checkBlankNumberSql = "SELECT * FROM ticketsales WHERE "
        + "ticketID = " + ticketID + ";";
        System.out.print("SELECT * FROM ticketsales WHERE "
            + "ticketID = " + ticketID + ";");
        try {
            pst = con.prepareStatement(checkBlankNumberSql);
            rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getString("status").equals("refunded")){
                    JOptionPane.showMessageDialog(this, "Error: ticket is already refunded");
                }
                else if(rs.getString("status").equals("sold")){
                    JOptionPane.showMessageDialog(this, "Error: ticket is not yet paid for");
                }else{

                    String query2="UPDATE ticketsales SET status='refunded' WHERE ticketID = "+ticketID+";";
                    pst =con.prepareStatement(query2);
                    pst.executeUpdate(query2);

                    String [] logContent = {ticketID, rs.getString("amount"), rs.getString("currency")};

                    CreateLog.writeLog("C:/Users/ASUS/Desktop/Team Project jin pages/java_system_with_GUI_Final (1)/java_system/LOGS FOR THE DEMO/RefundLog.txt", logContent);

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid ticket Number");
            }

        } catch (SQLException ex) {
            Logger.getLogger(travelAd.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_RefundTicketButtonActionPerformed

    private void VoidBlankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoidBlankButtonActionPerformed
        // TODO add your handling code here:
        String blankID= BlankNumberField.getText();
            Connection con=null;
         PreparedStatement pst;
         ResultSet rs;
        con=MyConnection.getConnection();
        String query = "SELECT * FROM blanks WHERE "
        + "blankID = " + blankID + ";";
        try {
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getString("status").equals("void")){
                    JOptionPane.showMessageDialog(this, "Error: ticket is already void");
                }
                else if(rs.getString("status").equals("sold")){
                    JOptionPane.showMessageDialog(this, "Error: ticket is already sold");
                }else{

                    String query2="UPDATE blanks SET status='void' WHERE blankID = "+blankID+";";
                    pst =con.prepareStatement(query2);
                    pst.executeUpdate(query2);

                    String [] logContent = {blankID};

                    CreateLog.writeLog("C:/Users/ASUS/Desktop/VoidLog.txt", logContent);

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid ticket Number");
            }

        } catch (SQLException ex) {
            Logger.getLogger(travelAd.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_VoidBlankButtonActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        if(StaffRoleLable.getText().equals("Travel_Advisor")){
        travelAd ta =new travelAd(StaffIDLabel.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        ta.setVisible(true);
        ta.pack();
        ta.setLocationRelativeTo(null); //puts in the center of the screen
      //  sls.setDefultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //hides previos page
        }else{
             officeManager manager = new officeManager(StaffIDLabel.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
             manager.setVisible(true);
             this.setVisible(false);
             manager.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        //Opens sales page when button is pressed on the TravelAd page
        Sales sls =new Sales(StaffIDLabel.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());
        sls.setVisible(true);
        sls.pack();
        sls.setLocationRelativeTo(null); //puts in the center of the screen
        this.dispose(); //hides previos page
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        IndividualSales isr = new IndividualSales(StaffIDLabel.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());

        isr.setVisible(true);
        isr.pack();
        isr.setLocationRelativeTo(null); //puts in the center of the screen
        this.dispose(); //hides previos page
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        RecordPayment rp = new RecordPayment(StaffIDLabel.getText(),
        StaffNameLable.getText(),
        StaffRoleLable.getText());

        rp.setVisible(true);
        rp.pack();
        rp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        // TODO add your handling code here:
        jPanel12.setBackground(new Color(81, 135, 194));
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        // TODO add your handling code here:
        jPanel12.setBackground(new Color(54,97,144));
    }//GEN-LAST:event_jPanel12MouseExited

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        loginFrame lf = new loginFrame();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252, 116, 117));
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        // TODO add your handling code here:
        jPanel15.setBackground(new Color(252,68,69));
    }//GEN-LAST:event_jPanel15MouseExited

    private void jPanel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseDragged
        int cordX= evt.getXOnScreen();
        int cordY = evt.getYOnScreen();

        this.setLocation(cordX-mousepX, cordY-mousepY);
    }//GEN-LAST:event_jPanel14MouseDragged

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel14MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(travelAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(travelAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(travelAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(travelAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new travelAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdvisorBlanksTable;
    private javax.swing.JTable AdvisorSaleTable;
    private javax.swing.JTextField BlankNumberField;
    private javax.swing.JButton BlankTableButton;
    private javax.swing.JComboBox<String> BlanksType;
    private javax.swing.JTextField CurrencyCodeField;
    private javax.swing.JTextField ExchangeRateField;
    private javax.swing.JButton RefundTicketButton;
    private javax.swing.JLabel StaffIDLabel;
    private javax.swing.JLabel StaffNameLable;
    private javax.swing.JLabel StaffRoleLable;
    private javax.swing.JTextField TicketNumberField;
    private javax.swing.JButton UpdateExchangeRateButton;
    private javax.swing.JButton VoidBlankButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
